<?xml version='1.0' encoding='utf-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.8</version>
        <relativePath />
    </parent>
    <groupId>ru.corelia</groupId>
    <artifactId>corelia-parent</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>
    <name>Corelia</name>
    <description>Настраиваемая платформа документооборота</description>
    <properties>
        <java.version>25</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>corelia-configuration</module>
        <module>corelia-config-compiler</module>
        <module>corelia-common</module>
        <module>corelia-platform-v</module>
        <module>corelia-auth</module>
        <module>corelia-document-service</module>
        <module>corelia-workflow-service</module>
        <module>corelia-attachment-service</module>
        <module>corelia-gateway</module>
        <module>corelia-system-tests</module>
    </modules>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <classifier>exec</classifier>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>